app:
  title: Backstage Demo
  baseUrl: http://localhost:3000
  support:
    url: https://github.com/backstage/backstage/issues
    items:
      - title: Backstage Community
        icon: chat
        links:
          - url: https://backstage.io/docs/overview/support
            title: Support and community
      - title: Backstage News
        icon: docs
        links:
          - url: https://backstage.io/blog/
            title: Backstage Blog

organization:
  name: Backstage

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'data:', 'https://backstage.io']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
      # apiBaseUrl: https://gitlab.example.com/api/v4
      # baseUrl: https://gitlab.example.com

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_DEVELOPMENT_CLIENT_ID}
        clientSecret: ${GITHUB_DEVELOPMENT_CLIENT_SECRET}
    gitlab:
      development:
        clientId: foo
        clientSecret: bar

catalog:
  readonly: true
  rules:
    - allow: [Component, API, System, Domain, Resource, Location, User, Group]
  locations:
    # Backstage example components
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Backstage example systems
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

    # Backstage example APIs
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # Backstage example organization groups
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

    # Backstage example domains
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-domains.yaml

    # Backstage example resources
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-resources.yaml

    # The backstage demo deployment (this)
    - type: url
      target: https://github.com/backstage/demo/blob/master/catalog-info.yaml

    # The backstage library repository
    - type: url
      target: https://github.com/backstage/backstage/blob/master/catalog-info.yaml

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers

# app-config.heroku.yaml replaces these values
# These configs here are required for config validation in CI to pass
techdocs:
  builder: 'external'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
